export const FETCH_BOARD_LIST = 'FETCH_BOARD_LIST'
export const FETCH_BOARD = 'FETCH_BOARD'
export const FETCH_PRODUCT_BOARD_LIST = 'FETCH_PRODUCT_BOARD_LIST'
export const FETCH_PRODUCT_BOARD = 'FETCH_PRODUCT_BOARD'